name: ecommerce_platform
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


  #-----------PACKAGES--------#
dependencies:
  flutter:
    sdk: flutter

    #Utility PACKAGES

    #Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  #State Management
  get: ^4.6.5


  #Product Specific

  #---------./ PACKAGES END ---------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true

  #--------Local Assets ------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/


  #-------- Local Fonts ------#


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
